apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  labels:
    app: client
spec:
  replicas: 8
  selector:
    matchLabels:
      container: client
  template:
    metadata:
      labels:
        container: client
    spec:
      terminationGracePeriodSeconds: 2
      imagePullSecrets: 
        - name: monadic5559eb9a-auth
      containers:
      - name: docker-headless-vnc-epotes-cli
        image: monadic.azurecr.io/docker-headless-vnc-epotes-cli:latest
        imagePullPolicy: Always
        args:
          ### make normal UI startup to connect via: oc rsh <pod-name> bash
          # - '--tail-log'
          - '--debug'
        ### checks that vnc server is up and running
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 2
          timeoutSeconds: 1
        ### checks if http-vnc connection is working
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 1
        resources:
        ports:
          # - containerPort: 5901
          #   protocol: TCP
          #   name: vnc
          - containerPort: 6901
            protocol: TCP
            name: http
        env:
          - name: SERVER
            value: server-service-epoptes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      container: server
  template:
    metadata:
      labels:
        container: server
    spec:
      terminationGracePeriodSeconds: 2
      imagePullSecrets: 
        - name: monadic5559eb9a-auth
      containers:
      - name: docker-headless-vnc-epotes-srv
        image: monadic.azurecr.io/docker-headless-vnc-epotes-srv:latest
        imagePullPolicy: Always
        args:
          ### make normal UI startup to connect via: oc rsh <pod-name> bash
          # - '--tail-log'
          - '--debug'
        ### checks that vnc server is up and running
        livenessProbe:
          tcpSocket:
            port: epoptes
          initialDelaySeconds: 2
          timeoutSeconds: 1
        ### checks if http-vnc connection is working
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 1
        ports:
          # - containerPort: 5901
          #   protocol: TCP
          #   name: vnc
          - containerPort: 6901
            protocol: TCP
            name: http
          - containerPort: 789
            protocol: TCP
            name: epoptes
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: server-service-epoptes
  labels:
    app: server
spec:
  selector:
    container: server
  ports:
  - name: epoptes-port-tcp
    protocol: TCP
    port: 789
    targetPort: epoptes
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: server-service-http
  labels:
    app: server
spec:
  selector:
    container: server
  ports:
  - name: http-port-tcp
    protocol: TCP
    port: 80
    targetPort: http
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-public
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: browser.0aa78c09b01d40a79e18.westus2.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-service-http
            port:
              number: 80
